[package]
name = "lorikeet"
version = "0.1.0"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "a parallel test runner for devops"
repository = "https://github.com/cetra3/lorikeet"

[dependencies]
petgraph = "*"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
tera = "*"
structopt = "0.1.0"
structopt-derive = "0.1.0"
threadpool = "*"
log = "*"
env_logger = "*"